spring:
  application:
    name: order-service

server:
  port: 9090

aws:
  region: ${AWS_REGION:eu-north-1}
  sqs:
    queue:
      name: ${SQS_QUEUE_NAME:MyQueue0}

logging:
  level:
    org.springframework: INFO