spring:
  datasource:
#    url: 'jdbc:h2:file:/data/demo'
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
#    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        validator:
          apply_to_ddl: false
#          check_nullability: true
    database-platform:
      org.hibernate.dialect.H2Dialect

#  http://localhost:8080/h2-console
#  The web console has an auto-complete feature that suggests SQL keywords.
#  The fact that the console is lightweight makes it handy for visually inspecting the database or executing raw SQL directly.
#  we set spring.h2.console.settings.trace to false to prevent trace output,
#  and we can also disable remote access by setting spring.h2.console.settings.web-allow-others to false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
#        web-allow-others: false



logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type: TRACE
    org.springframework: INFO